# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170303_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='long_desc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
